### PR TITLE
Style updates for data service frontend

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes https://github.com/open-sdg/open-sdg/issues/1197
Fixes https://github.com/open-sdg/open-sdg/issues/1198
Fixes https://github.com/open-sdg/open-sdg/issues/1196

Link: https://lucygwilliamadmin.github.io/sdg-data-sandpit/

### CODE REVIEW

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin Sorry is there a link somewhere i'm missing?

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner just added

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin @brockfanning this looks good - thank you. My only comment is that we could probably tweak the content and button labelling on this page: https://lucygwilliamadmin.github.io/sdg-data-sandpit/. But I think that is a different ticket for the future. :)

**Review by LucyGwilliamAdmin — APPROVED** [review]
Approving based on Phill's comment

**Pull request merged**
