### PR TITLE
Input/output classes

### PR DESCRIPTION
**Pull request by brockfanning**
Here's a beginning to a possible approach for #4, with a few types of classes:
* 2 "Input" classes: CSV data, and YAML/Markdown metadata
* 1 "Output" class: Open SDG format
* A basic class for indicators

This could use more testing, but a brief run locally seemed to work. Here is a snippet of how it would be used:
```
import os
import sdg

data_pattern = os.path.join('data', '*-*.csv')
data_input = sdg.inputs.InputCsvData(path_pattern=data_pattern)

meta_pattern = os.path.join('meta', '*-*.md')
meta_input = sdg.inputs.InputYamlMdMeta(path_pattern=meta_pattern)

inputs = [data_input, meta_input]

opensdg_output = sdg.outputs.OutputOpenSdg(inputs, output_folder='_site', schema_path='_prose.yml')
outputs = [opensdg_output]

sdg.build_data(outputs=outputs)
```

In theory this is not a breaking change, since it just adds a new optional param to build_data().

I say this is a "beginning" because right now the classes are still using the procedural functions from data.py, json.py, etc.. I assume that we'd probably want all that logic to live inside the appropriate class.

Also, I'm new to Python OOP standards to any feedback or advice is quite welcome.

### CODE REVIEW

**Comment by dougmet** [comment]
Hi Brock, thanks for this. I'd like to spend a little bit of time staring at it before merging in (but I like the approach). I hadn't considered different classes for different types of input (I was essentially thinking of one indicator class with different types of input method). But actually I quite like it, and it should be easy to test too.

**Comment by brockfanning** [comment]
Cool, and to give you some idea of where I'm thinking it might go - other input classes might include InputSdmxApi and InputSdmxFile (#9), and other output classes might include OutputSdmx (#15) and OutputGeoJson (https://github.com/open-sdg/open-sdg/issues/74).

I'll fix the conflicts shortly and update the PR.

**Comment by brockfanning** [comment]
Another note - I didn't carry over the `git_data_dir` parameter into the OOP approach, which is what the US is using to support "wide" CSV data. It would be easy to carry it over, but my thinking was that instead the US might want to first investigate making an InputCsvDataWide subclass.

**Comment by brockfanning** [comment]
Great point, I will refactor that.

**Comment by brockfanning** [comment]
@dougmet This is ready again for you to review.

**Pull request merged**
