### PR TITLE
Provide indicator_id when altering data/metadata

### PR DESCRIPTION
**Pull request by brockfanning**
Q | A
--- | ---
Feature branch/test site URL | [Link](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-input-alteration-context/1-2-1/)
Fixed issues | Fixes #ISSUENUMBER
Related version | 1.7.0-dev
Bugfix, feature or docs? | feature
* [x] Keeps backward-compatibility
* [ ] Includes tests
* [x] Updated docs
* [ ] Updated config forms
* [ ] Added CHANGELOG entry

### CODE REVIEW

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Do you think this could be added for 1.7.0? This functionality would be helpful for Vanuatu.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I don't see why not. Will need to refresh my memory and then can give it a test

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning so what would [this](https://github.com/ONSdigital/sdg-data/blob/develop/scripts/build_data.py#L36) (`def alter_meta(meta)`)?

a. `def alter_meta(meta, context)`
b. `def alter_meta(meta,  indicator_id=indicator_id)`

I've been looking in the files changed tab but unsure

**Review by LucyGwilliamAdmin — APPROVED** [review]
Tested this out by trying to remove a column for a specific indicator:
https://github.com/ONSdigital/sdg-data/blob/feature-input-alteration-context/scripts/build_data.py#L66-L70

Works well - column was removed:
http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-input-alteration-context/1-2-1/

**Pull request merged**
