### PR TITLE
SDMX output by goal

### PR DESCRIPTION
**Pull request by brockfanning**
Because SDMX data and metadata can be combined arbitrarily, it's not too hard to group them by goal. This may be useful for some cases. One immediate use-case is that the "all.xml" files (when full) are too big to be uploaded into UNSD's SDG Lab -- the upload fails. This means each indicator needs to be uploaded separately. Grouping them by goal makes this process much easier (17 uploads instead of 200+).

[Here's an example of this in action](http://brock.tips/fcdo/burundi/sdg-build/sdmx-output.html).

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning should have asked before I started testing but is this ready for review?

My findings so far:

- Goal files have no validation errors
- However, it does seem that some of the series that are in the goal 1 file don't belong to goal 1 indicators (haven't checked other goals). E.g.
  - SH_H2O_SAFE (6.6.1)
  - IT_MOB_OWN (5.b.1)

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I thought it was ready, but that does seem wrong. I'll look into that, thanks for catching it.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I'm realizing that the discrepancy you noticed is a bug in the source data of that example, but not a bug from this PR. Here is another example using Kyrgyzstan's data which should be more correct: http://brock.tips/fcdo-kg-data/

**Review by LucyGwilliamAdmin — APPROVED** [review]
Looks good based on Kyrgyzstan goal output

**Pull request merged**
