### PR TITLE
Allow column and code mappings to be used

### PR DESCRIPTION
**Pull request by LucyGwilliamAdmin**

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I think I must have done something wrong as I'm getting this error:
https://github.com/ONSdigital/sdg-sdmx-data/runs/2220458700?check_suite_focus=true

I'm not really sure what it means though?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I think I snuck a bug in with the last PR. I just opened a PR that should fix that: https://github.com/open-sdg/sdg-build/pull/237.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I merged that PR, so I'd recommend merging the latest 1.4.0-dev into this branch.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning ok thanks, that fixed the error I was getting - terms are being mapped correctly and SDG Lab is accepting the output - is there anything else that needs to be tested?

**Review by brockfanning — APPROVED** [review]
@LucyGwilliamAdmin Cool, looks good to me!

**Pull request merged**
