### PR TITLE
SDMX output: StructureSpecific

### LINKED ISSUE #205: SDMX output - support StructureSpecific
I think right now our SDMX output is always GenericData. But since the UNSD SDG Lab requires StructureSpecific, we should allow for that option. In think it will be an easy thing to add thanks to the sdmx Python library we're leveraging.

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #205 

With version 2.3.0 of the sdmx library, we can now produce StructureSpecific output. This PR makes this the default for Open SDG output, and also makes it an optional parameter.

### CODE REVIEW

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Not urgent, but I thought you might be interested in this. You can see this in action here: https://kazstat.github.io/sdg-data-kazstat/sdmx-output.html

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning this is great! You can get a file with all data in as well??

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin You mean the "all.xml"? Yep that is already a feature of the OutputSdmxMl class.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I think you might have said somewhere else, but is structure specific required for SDG Lab?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Yes it is.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning what's the best way to test this? I've merged these changes into my sdmx-mapping-2 branch and now using that on UK sandpit and structure specific xmls are being outputted.

I've just ran it through web SDMX converter to validate and all fine, so now about to try loading to SDG Lab to see if successful

**Comment by LucyGwilliamAdmin** [comment]
Ok so 5/5 individual files and the all file passed the validation. 5/5 individual files could be uploaded to SDG Lab but when I try to upload the all file to SDG Lab, it doesn't work but I don't know if it's supposed to?

Aside from that, is there anything else I should test?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning Daniel has just confirmed that SDG Lab accepts both single and multi-series files.

I think I see the problem and possibly not related to this - I've just revisited my multi-series file and it seems some parts of header are missing e.g. ID, Prepared, Sender:

https://onsdigital.github.io/sdg-sdmx-data/sdmx/all.xml

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Ah OK, makes sense. I think we can fix that in a separate PR.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning how do I configure whether or not structure specific is used?

I assumed I would need to add `structure_specific` option but I'm getting this error and I've tried setting it to False and false (both gave the same error):
https://github.com/ONSdigital/sdg-sdmx-data/runs/2142432493?check_suite_focus=true#step:5:15

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin For Open SDG I assumed that we would always want StructureSpecific, so I hardcoded that. I can remove the hardcoding if you think it should be optional.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I think it's fine to have that as only option - I just seen in description that it had been added as an optional parameter so was just trying to test it

**Review by LucyGwilliamAdmin — APPROVED** [review]
Approving as platform is outputting structure specific SDMX files which are passing validation and are being accepted by SDG Lab

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Should I remove the concept_map stuff before merging?

Also I think I can tweak it so that structure_specific can be set to false without causing an error - with true still being the default.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning yes please remove the mapping stuff - forgot about that

I'm fine with it not being optional but if it's a quick thing, then I don't see the harm in it making it so - what are your thoughts?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Making optional is easy - I've just pushed that, and also removed the concept_map code for now.

**Pull request merged**
