### PR TITLE
Allow translations in CSV format

### PR DESCRIPTION
**Pull request by LucyGwilliamAdmin**

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning - I quickly put this together for #86 and I'm trying it with Kyrgyzstan site but I seem to be getting this error on [CircleCI](https://circleci.com/gh/sdg-kyrgyzstan/open-sdg-data-starter/3005) so not sure if I've missed something in this PR

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Sometimes CircleCI's caching can prevent changes to a dependency from showing up. I suspect that's what's happening. As we have it set up now, there are only two ways to "bust" the cache:
1. Change the requirements.txt file in some way. (Maybe adding a comment on a new line at the top like "# Updated 1/17/2020" would work?)
2. Increment the cache keys in the [.circleci/config.yml file](https://github.com/sdg-kyrgyzstan/open-sdg-data-starter/blob/develop/.circleci/config.yml). Eg, changing all instances of "test-dependencies-v2" to "test-dependencies-v3".

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin To clarify, in #1 above I'm referring to the requirements.txt file in your data repository.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning great 1 worked - Kyrgyzstan's site is now using this approach for data label translations. Thanks for your help

**Pull request merged**
