### PR TITLE
Vary by language in some method caches

### PR DESCRIPTION
**Pull request by brockfanning**
This fixes a bug where the GeoJSON output doesn't build correctly in the non-default languages. This bug has the effect in Open SDG of preventing maps from working in non-default languages, so this would be an important fix to get in for 1.4.0, I think.

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning was this bug reported by someone? Just asking before I try to recreate and test fix

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin No, I only noticed this while trying to set up maps for a multilingual site (Cambodia).

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning ok, thanks - is this working for them? or should I do separate test?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Yes, it's working well, here's an example with a map: https://sdg-cambodia.github.io/site/2-2-1/

**Review by LucyGwilliamAdmin — APPROVED** [review]
Looks good on Cambodia example

**Pull request merged**
