### PR TITLE
Print warning instead of exception when series has duplicate value

### PR DESCRIPTION
**Pull request by brockfanning**
This allows builds to complete even when there are issues in the data.

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning this is great - much easier to see where the issues are - wondering if the indicator code could also be in the warning?

**Comment by LucyGwilliamAdmin** [comment]
Here's how warning looks:
https://travis-ci.org/github/ONSdigital/sdg-data

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Thanks - any feedback? Is it helpful enough?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Sorry, missed earlier comment. I'll see about the indicator code, though I think that might be tricky.

**Comment by LucyGwilliamAdmin** [comment]
No problem if not - I'm mainly just thinking about if someone is bulk uploading.

I'm sure there's enough info for someone to be able to work what indicator the series belongs to!

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I just pushed up an attempt - can you give it a try?

**Pull request merged**
