### PR TITLE
Allow missing values in reporting status extra fields

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes https://github.com/open-sdg/open-sdg/issues/1010

This just needs a translation. I have the translation key as `status.not_specified`, thinking the English translation will be "Not specified", but it can be changed as needed.

### CODE REVIEW

**Review by LucyGwilliamAdmin — APPROVED** [review]
This works well:
https://lucygwilliamadmin.github.io/open-sdg-site-starter-1/en/reporting-status/

image

Side note: how would I translate indicator_type here again? Would it come under status translations?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I believe the best way is to specify the "translation_key" properties in the schema file. For example here is how Kazakhstan is translating one of their custom metadata fields: https://github.com/kazstat/sdg-data-kazstat/blob/develop/_prose.yml#L70-L88

Do you think "Not specified" is the best English here? If so I will add it to SDG Translations so it can be translated into the other languages.

**Comment by LucyGwilliamAdmin** [comment]
I think "Not specified" works - clear and true. The other one I thought of was "Other" but that may lead people to think that the country specified it as "Other!

**Comment by LucyGwilliamAdmin** [comment]
Also just tried the prose thing for the translation - that worked. Thanks :)

**Pull request merged**
