### PR TITLE
Always set all dimensions in SDMX output

### PR DESCRIPTION
**Pull request by brockfanning**
In SDMX all of the dimensions are required for each series. So the output here should always set each dimension, regardless of whether there is a value or not. If not, it should always use the default value.

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning can latest be pulled in from 1.4.0 so I can make use of the updated sdmx library please?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I think it should be there - it's not showing in Github but I've merged the latest code to this branch.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning looks good to me:

https://onsdigital.github.io/sdg-sdmx-data/sdmx/3-2-1.xml

**Review by LucyGwilliamAdmin — APPROVED** [review]

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Since we're about to push a hotfix release 1.3.1, we have the choice of whether to put this in 1.3.1 or wait for 1.4.0. Thoughts?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I think this is fine to go into 1.3.1 hotfix since it's kind of a bug

**Pull request merged**
