### PR TITLE
Allow multiple data inputs for the same indicator

### PR DESCRIPTION
**Pull request by brockfanning**
@LucyGwilliamAdmin Here is an updated version of this PR. I believe this should get some very critical testing - with both single and multiple data inputs, to ensure there is no unintended consequence.

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning once #293 has been merged, is it possible for the latest code to be pulled in here so I can use the global SDMX API as an input please?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Yes, that's done.

**Comment by LucyGwilliamAdmin** [comment]
Testing checklist
[ ] 1 source
[ ] 2 source - different series coming from two sources
[ ] 2 source - data for same series coming from two sources e.g. different disaggs

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I've added some scenarios that I'm testing above - can you think of any others?

**Pull request merged**
