### PR TITLE
Inputs for data/metadata from AfDB's Open Data Portal

### LINKED ISSUE #216: Input data from AfDB's Open Data Platform
The African Development Bank Group's [Open Data Platform](https://dataportal.opendataforafrica.org/) is used by many countries in Africa for management of SDG data. We could add an input to make it easier to process data from the AfDB Open Data Platform.

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #216 

A couple examples of usage:
* [This configuration](https://github.com/brockfanning/fcdo/blob/main/scripts/sdg-build-config/burundi.yml) is producing [this build](http://brock.tips/fcdo/burundi/sdg-build/)
* [This configuration](https://github.com/brockfanning/fcdo/blob/main/scripts/sdg-build-config/ethiopia.yml) is producing [this build](http://brock.tips/fcdo/ethiopia/sdg-build/)

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning are the jsons (e.g. https://github.com/brockfanning/fcdo/blob/main/scripts/sdg-build-config/input-data/ethiopia.json) what are outputted from the Open Data Platforms?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning is there anymore you wanted to do at this stage or did you want to push it through as it is for 1.4.0?

**Comment by brockfanning** [comment]
I may need to take another look - if only to resolve those conflicts. I'm happy to leave this for a later release.

**Comment by brockfanning** [comment]
This PR has been open for a while, and there is no clear user need, so I'll go ahead and close this.

**Pull request closed without merging**
