### PR TITLE
SDMX output - extend DSD

### PR DESCRIPTION
**Pull request by brockfanning**
This adds an `extend_dsd` parameter to the SDMX output, which can take the disaggregation values from your data and use them to extend the codelists in the DSD. It also adds a `dsd_languages` parameter which can be used to add translations to all codes in the DSD, if you have matching translations.

One use-case for this is to allow the use of the SDMX output even if a DSD has not been created - you can use the global DSD and then use `extend_dsd` to add your disaggregation values to the global codelists.

For example, instead of:

```
sdmx_output:
  dsd: my-dsd.xml
```

You could do:

```
sdmx_output:
  dsd: https://registry.sdmx.org/ws/public/sdmxapi/rest/datastructure/IAEG-SDGs/SDG/latest/?format=sdmx-2.1&detail=full&references=children
  extend_dsd: true
```

And since the `dsd` parameter actually defaults to that, you could just do:

```
sdmx_output:
  extend_dsd: true
```

The `dsd_languages` is just a way to add your translations to the DSD. These translations are not used by sdg-build -- or open-sdg -- but may be useful for other consumers of the DSD. To describe how it would work, assume that you have a translation file called `URBANISATION.yml` which contains the Russian translation `U: Город`. Then if you have this config:

```
sdmx_output:
  extend_dsd: true
  dsd_languages:
    - en
```

Then the DSD would be altered so that in the codelist for URBANISATION it will add a Russian translation for the `U` code. For example:

```
<str:Code id="U" urn="urn:sdmx:org.sdmx.infomodel.codelist.Code=IAEG-SDGs:CL_URBANISATION(1.0).U">
  <com:Name xml:lang="en">Urban</com:Name>
  <com:Name xml:lang="ru">Город</com:Name>
</str:Code>
```

### CODE REVIEW

**Comment by brockfanning** [comment]
To see an example, this is in use [here](https://kazstat.github.io/sdg-data-kazstat/sdmx-output.html) using this [config](https://github.com/kazstat/sdg-data-kazstat/blob/develop/config_data.yml#L85-L90).

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning does this require any extra testing on top of what you've done with Kazakhstan?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I wonder if we should add some validation to this. For example, requiring that all codes have no spaces in them. Should this feature raise an exception if a code has a space in it, maybe? That would be a tell-tale sign that the data is probably not SDMX-compliant. For example, if a data provider accidentally put "My disaggregation value" in a CSV file, instead of "_L_ABC123".

**Comment by brockfanning** [comment]
The latest commit issues a warning if any codes have spaces in them. I opted not to raise an exception at this point.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning could this be updated with latest code when you have a chance please as I'm getting an error which I think a PR has been merged for

**Comment by brockfanning** [comment]
I just merged it - though I don't have time at the moment to test this. I had to make some changes in order to resolve conflicts, so would feel better if it got another test.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning the DSD I'm inputting is https://registry.sdmx.org/ws/public/sdmxapi/rest/datastructure/IAEG-SDGs/SDG/latest/?format=sdmx-2.1&detail=full&references=children and I'm setting extend_dsd to true.

However, I'm getting quite a few errors for the DSD that is being outputted when I try to validate.

It's quite difficult to see them all but to start it seems that some elements are getting removed.

Error: Invalid content was found starting with element '{"http://www.sdmx.org/resources/sdmxml/schemas/v2_1/common":Description}'. One of '{"http://www.sdmx.org/resources/sdmxml/schemas/v2_1/common":Annotations, "http://www.sdmx.org/resources/sdmxml/schemas/v2_1/common":Name}' is expected.line/column: 13/42

Input DSD:

```
<str:OrganisationSchemes>
  <str:AgencyScheme urn="urn:sdmx:org.sdmx.infomodel.base.AgencyScheme=SDMX:AGENCIES(1.0)" isExternalReference="false" agencyID="SDMX" id="AGENCIES" isFinal="false" version="1.0">
    <com:Name xml:lang="en">SDMX Agency Scheme</com:Name>
    <str:Agency urn="urn:sdmx:org.sdmx.infomodel.base.Agency=SDMX" id="SDMX">
      <com:Name xml:lang="en">SDMX</com:Name>
      <com:Description xml:lang="en">SDMX is an initiative to foster standards for the exchange of statistical information. It is sponsored by the Bank for International Settlements (BIS), the European Central Bank (ECB), the Statistical Office of the European Union (Eurostat), the International Monetary Fund (IMF), the Organization for Economic Co-Operation and Development (OECD), the United Nations (UN) and the World Bank.</com:Description>
      <str:Contact>
        <com:Name xml:lang="en">SDMX Secretariat</com:Name>
        <str:Department xml:lang="en">SDMX Secretariat</str:Department>
        <str:Role xml:lang="en">Single entry point for external inquiries</str:Role>
        <str:URI>http://sdmx.org</str:URI>
        <str:Email>secretariat@sdmx.org</str:Email>
      </str:Contact>
    </str:Agency>
    <str:Agency urn="urn:sdmx:org.sdmx.infomodel.base.Agency=IMF" id="IMF">
      <com:Name xml:lang="en">International Monetary Fund (IMF)</com:Name>
      <com:Description xml:lang="en">The IMF works to foster global growth and economic stability. It provides policy advice and financing to members in economic difficulties and also works with developing nations to help them achieve macroeconomic stability and reduce poverty.</com:Description>
      <str:Contact>
        <com:Name xml:lang="en">Single point of contact for external inquiries</com:Name>
        <str:Department xml:lang="en">Statistics Department</str:Department>
        <str:Role xml:lang="en">Single point of contact for external inquiries</str:Role>
        <str:URI>http://www.imf.org</str:URI>
        <str:Email>StatisticsQuery@imf.org</str:Email>
      </str:Contact>
    </str:Agency>
```

Output DSD:

```
<str:OrganisationSchemes>
  <str:AgencyScheme version="1.0" isExternalReference="false" isFinal="false" agencyID="SDMX" id="AGENCIES" urn="urn:sdmx:org.sdmx.infomodel.base.AgencyScheme=SDMX:AGENCIES(1.0)">
    <com:Name xml:lang="en">SDMX Agency Scheme</com:Name>
    <str:Agency id="SDMX" urn="urn:sdmx:org.sdmx.infomodel.base.Agency=SDMX">
        <com:Description xml:lang="en">SDMX is an initiative to foster standards for the exchange of statistical information. It is sponsored by the Bank for International Settlements (BIS), the European Central Bank (ECB), the Statistical Office of the European Union (Eurostat), the International Monetary Fund (IMF), the Organization for Economic Co-Operation and Development (OECD), the United Nations (UN) and the World Bank.</com:Description>
    </str:Agency>
    <str:Agency id="IMF" urn="urn:sdmx:org.sdmx.infomodel.base.Agency=IMF">
        <com:Description xml:lang="en">The IMF works to foster global growth and economic stability. It provides policy advice and financing to members in economic difficulties and also works with developing nations to help them achieve macroeconomic stability and reduce poverty.</com:Description>
    </str:Agency>
```

**Pull request closed without merging**
