### PR TITLE
Allow the export filename to be configured

### PR DESCRIPTION
**Pull request by brockfanning**
Fixes #679

The data config setting to test here is: `indicator_export_filename`, and should be the desired filename without the extension. For example:

`indicator_export_filename: uk_sdg_indicators`

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning have just tried testing this but it didn't seem to work. Here's my data config change:
https://github.com/ONSdigital/sdg-data/blob/configurable-indicator-download-filename/config_data.yml#L94

and see zip file info here:
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/data/configurable-indicator-download-filename/open-sdg-output.html

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I hadn't thought this one all the way through - but I believe I've caught everything now. This will also need a [corresponding PR in open-sdg](https://github.com/open-sdg/open-sdg/pull/1061) or else the link on site will be broken.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning thanks - i've just rebuilt the feature branch:
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/data/configurable-indicator-download-filename/open-sdg-output.html

I'm wondering if the name of the json file should be change as well?

**Review by LucyGwilliamAdmin — APPROVED** [review]
Ah ok cool - happy to approve then

**Pull request merged**
